modLoader = "javafml"
loaderVersion = "[40,)"
license = "MIT"
issueTrackerURL="https://github.com/LimonBlaze/origins-classes-forge/issues"

[[mods]]
modId = "origins_classes"
version = "${version}"
displayName = "Origins: Classes"
displayURL="https://github.com/LimonBlaze/origins-classes-forge/"
logoFile="pack.png"
credits="Thanks Apace for the original work, and thanks EdwinMindcraft for the forge port!"
authors="LimonBlaze"
description = "An add-on for the Origins mod which adds classes to the game."

[[dependencies.origins_classes]]
modId = "minecraft"
mandatory = true
versionRange = "${mc_requirements}"
ordering = "NONE"
side = "BOTH"

[[dependencies.origins_classes]]
modId = "forge"
mandatory = true
versionRange = "${forge_requirements}"
ordering = "NONE"
side = "BOTH"

[[dependencies.origins_classes]]
modId = "origins"
mandatory = true
versionRange = "${origins_requirements}"
ordering = "NONE"
side = "BOTH"
