modLoader = "javafml"
loaderVersion = "[39,)"
license = "MIT"
issueTrackerURL="https://github.com/LimonBlaze/origins-classes-forge/issues"

[[mods]]
modId = "origins_classes"
version = "${version}"
displayName = "Origins: Classes"
displayURL="https://github.com/LimonBlaze/origins-classes-forge/"
logoFile="icon.png"
credits="Thanks Apace for the original work, and thanks EdwinMindcraft for the forge port!"
authors="LimonBlaze"
description = "An add-on for the Origins mod which adds classes to the game."

[[dependencies.origins-classes]]
modId = "forge"
mandatory = true
versionRange = "[39,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.origins-classes]]
modId = "minecraft"
mandatory = true
versionRange = "[1.18.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.origins-classes]]
modId = "origins"
mandatory = true
versionRange = "[1.3.1.14,)"
ordering = "NONE"
side = "BOTH"
